new Vue({
    el: '#zhiqinfootball',
    data: {
        sortType: 'number',
        searchText: '',
        minNumber: '',
        maxNumber: '',
        selectedPosition: [],
        positions: ['GK', 'RB', 'CB', 'LB', 'RM', 'CM', 'LM', 'CF'],
        players: [{
                number: '3',
                name: '晉 丞',
                info: '二年級時加入球隊，對自己要求甚高，在場下總是默默苦練精進自己的體能和技術，場上則是無論前鋒或後衛都能夠勝任，擅長控球與創造得分機會。',
                active: true,
                position: ['RB', 'CB', 'RM', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '2',
                    gs: '0',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '3',
                    gs: '2',
                    goals: '3',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '7',
                    gs: '1',
                    goals: '2',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '3',
                    goals: '1',
                    asts: '2',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '3',
                    goals: '3',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '臺北市足球Ｕ聯賽',
                    g: '1',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制秋季聯賽',
                    g: '5',
                    gs: '5',
                    goals: '4',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '春季大安盃',
                    g: '1',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '包中盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制春季聯賽',
                    g: '6',
                    gs: '2',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '迎虎盃',
                    g: '3',
                    gs: '2',
                    goals: '3',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: 'A-Star聖誕盃',
                    g: '2',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '新北聯合盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '中正主委盃',
                    g: '3',
                    gs: '0',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '學童盃',
                    g: '1',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '春季大安盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '萬歲盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '金牛賀歲盃',
                    g: '1',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '扶輪社暨航源足球賽',
                    g: '4',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '2',
                    goals: '2',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北迷你盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }]
            },
            {
                number: '7',
                name: '黃 衍',
                info: '球隊元老成員之一，有著出色的速度和身體條件，身為一匹邊路快馬，是進攻時撕裂對手防線的核心人物。偶爾客串守門員，對撲救點球亦相當有心得。',
                active: true,
                position: ['GK', 'LB', 'RM', 'LM', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '5',
                    gs: '0',
                    goals: '3',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '3',
                    gs: '2',
                    goals: '4',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '4',
                    gs: '4',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '4',
                    goals: '4',
                    asts: '1',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '4',
                    goals: '2',
                    asts: '0',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制秋季聯賽',
                    g: '5',
                    gs: '5',
                    goals: '4',
                    asts: '2',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市夏季主委盃草地五人制',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '1',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '臺北市五人制足球聯賽',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '包中盃',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '臺北市教育盃',
                    g: '3',
                    gs: '2',
                    goals: '2',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制春季聯賽',
                    g: '6',
                    gs: '6',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '迎虎盃',
                    g: '3',
                    gs: '3',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: 'A-Star聖誕盃',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '3',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '中正主委盃',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '學童盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '春季大安盃',
                    g: '6',
                    gs: '5',
                    goals: '4',
                    asts: '4',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '金牛賀歲盃',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '扶輪社暨航源足球賽',
                    g: '5',
                    gs: '5',
                    goals: '2',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北聯合盃',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '秋季大安盃',
                    g: '6',
                    gs: '5',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }]
            },
            {
                number: '9',
                name: '紘 豪',
                info: '一年級時加入球隊，在防守端下足苦功，是球隊後防不可缺少的大將。進入中年級後亦加強了進攻意識與技巧，向全能球員之路邁進。',
                active: true,
                position: ['RB', 'LB', 'RM'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '1',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '5',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '1',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '臺北市足球Ｕ聯賽',
                    g: '1',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制秋季聯賽',
                    g: '5',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '春季大安盃',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '包中盃',
                    g: '3',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制春季聯賽',
                    g: '4',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '迎虎盃',
                    g: '3',
                    gs: '2',
                    goals: '2',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: 'A-Star聖誕盃',
                    g: '2',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '學童盃',
                    g: '1',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '春季大安盃',
                    g: '6',
                    gs: '0',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '萬歲盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '金牛賀歲盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '扶輪社暨航源足球賽',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '4',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '秋季大安盃',
                    g: '6',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }]
            },
            {
                number: '10',
                name: '善 捷',
                info: '帶著在俱樂部鍛練出的技術與天賦，於二年級下學期時加入球隊。長期在球隊後防上提供穩定的力量，把守大門的功力亦十分了得。',
                active: true,
                position: ['GK', 'RB', 'LB'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '1',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '1',
                    cs: '2'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制秋季聯賽',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '4',
                    goals: '0',
                    asts: '0',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '新北市夏季主委盃草地五人制',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '春季大安盃',
                    g: '4',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '包中盃',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '臺北市教育盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制春季聯賽',
                    g: '1',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '迎虎盃',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: 'A-Star聖誕盃',
                    g: '3',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '新北聯合盃',
                    g: '2',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '中正主委盃',
                    g: '3',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '學童盃',
                    g: '1',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '安聯小小世界盃',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '春季大安盃',
                    g: '6',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '5'
                }, {
                    year: '2021',
                    cup: '萬歲盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '金牛賀歲盃',
                    g: '3',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '扶輪社暨航源足球賽',
                    g: '5',
                    gs: '3',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北迷你盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }]
            },
            {
                number: '12',
                name: '皓 宇',
                info: '身為球隊創隊學長的弟弟，開啟足球之路的時間相當早，本身的速度和傳球意識在隊內皆屬頂尖，是能擔任前鋒、邊路或中場指揮官等多種角色的多面手。',
                active: true,
                position: ['RM', 'CM', 'LM', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '5',
                    gs: '3',
                    goals: '2',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '2',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '5',
                    gs: '0',
                    goals: '2',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '2',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '臺北市足球Ｕ聯賽',
                    g: '1',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市少年八人制秋季聯賽',
                    g: '5',
                    gs: '2',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北市夏季主委盃草地五人制',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '臺北市五人制足球聯賽',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '中華五人制足球錦標賽',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '臺北市教育盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '迎虎盃',
                    g: '3',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: 'A-Star聖誕盃',
                    g: '3',
                    gs: '3',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '新北聯合盃',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '中正主委盃',
                    g: '3',
                    gs: '1',
                    goals: '0',
                    asts: '2',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '學童盃',
                    g: '2',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '安聯小小世界盃',
                    g: '3',
                    gs: '3',
                    goals: '5',
                    asts: '2',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '春季大安盃',
                    g: '6',
                    gs: '1',
                    goals: '9',
                    asts: '6',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '金牛賀歲盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '扶輪社暨航源足球賽',
                    g: '5',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '秋季大安盃',
                    g: '6',
                    gs: '2',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }]
            },
            {
                number: '13',
                name: '邁 可',
                info: '四年級才加入球隊的新兵，憑藉早年在俱樂部打下的基礎快速跟上球隊的腳步。有著極好的身材條件和無限的潛力，在增加比賽經驗的道路上持續前進。',
                active: true,
                position: ['CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '2',
                    gs: '0',
                    goals: '1',
                    asts: '2',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '黃蜂盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }]
            },
            {
                number: '15',
                name: '凱 泰',
                info: '早期就加入球隊的元老之一，天姿聰穎與積極正向是他的註冊商標，有著人高手長等成為頂級守門員的絕佳條件，曾多次在比賽中為球隊守住大門。',
                active: true,
                position: ['GK', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '黃蜂盃',
                    g: '2',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '1',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '3',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '2'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '1'
                }, {
                    year: "2022",
                    cup: "臺北市足球Ｕ聯賽",
                    g: "1",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制秋季聯賽",
                    g: "4",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "3"
                }, {
                    year: "2022",
                    cup: "新北市夏季主委盃草地五人制",
                    g: "3",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "春季大安盃",
                    g: "3",
                    gs: '0',
                    goals: "0",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制春季聯賽",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "1"
                }, {
                    year: "2021",
                    cup: "A-Star聖誕盃",
                    g: "3",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "新北聯合盃",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "中正主委盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "1"
                }, {
                    year: "2021",
                    cup: "學童盃",
                    g: "1",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "萬歲盃",
                    g: "2",
                    gs: '2',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "金牛賀歲盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "2"
                }, {
                    year: "2021",
                    cup: "扶輪社暨航源足球賽",
                    g: "3",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "1"
                }, {
                    year: "2020",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "1"
                }, {
                    year: '2020',
                    cup: '新北迷你盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }]
            },
            {
                number: '18',
                name: '維 恩（C）',
                info: '球隊的創隊元老之一，因早年便和哥哥一起踢球，在心態和技術上都有十分超齡的表現。目前擔任球隊隊長的他，用全能的身手帶領著大家立下無數戰功，是球隊最重要支柱。',
                active: true,
                position: ['GK', 'CB', 'CM'],
                appearance: [{
                    year: '2023',
                    cup: '國小世界盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '明道盃',
                    g: '5',
                    gs: '5',
                    goals: '0',
                    asts: '3',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '2',
                    gs: '2',
                    goals: '2',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '中正盃',
                    g: '6',
                    gs: '6',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '7',
                    gs: '7',
                    goals: '6',
                    asts: '4',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '4',
                    goals: '1',
                    asts: '2',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '4',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }, {
                    year: "2022",
                    cup: "臺北市足球Ｕ聯賽",
                    g: "1",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制秋季聯賽",
                    g: "5",
                    gs: '4',
                    goals: "5",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市夏季主委盃草地五人制",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市五人制足球聯賽",
                    g: "2",
                    gs: '2',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "包中盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "中華五人制足球錦標賽",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市教育盃",
                    g: "3",
                    gs: '3',
                    goals: "4",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制春季聯賽",
                    g: "6",
                    gs: '6',
                    goals: "1",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "迎虎盃",
                    g: "3",
                    gs: '3',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "A-Star聖誕盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "中正主委盃",
                    g: "3",
                    gs: '3',
                    goals: "2",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "學童盃",
                    g: "2",
                    gs: '2',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "6",
                    gs: '6',
                    goals: "5",
                    asts: "2",
                    cs: "3"
                }, {
                    year: "2021",
                    cup: "金牛賀歲盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "扶輪社暨航源足球賽",
                    g: "5",
                    gs: '5',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '4',
                    goals: "3",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "秋季大安盃",
                    g: "6",
                    gs: '5',
                    goals: "1",
                    asts: "2",
                    cs: "0"
                }]
            },
            // {
            //     number: '20',
            //     name: '瑀 東',
            //     info: '四年級加入球隊的新血，亦是隊上最後一位新增的成員。雖然加入前沒受過太多足球訓練，在他身上卻看不到新手的生澀，常有讓人驚艷的表現。',
            //     active: true,
            //     position: [''],
            //     appearance: [{
            //         year: '',
            //         cup: '',
            //         g: '',
            //         gs: '0',
            //         goals: '0',
            //         asts: '0',
            //         cs: '0'
            //     }]
            // },
            {
                number: '21',
                name: '亮 谷（VC）',
                info: '二年級加入球隊時表現就已相當亮眼，身為球隊裡足球知識最豐富的小博士，有著頂級的視野、傳球和閱讀比賽的能力。是擔任球場大腦、中場指揮官的不二人選。',
                active: true,
                position: ['CB', 'RM', 'CM', 'LM'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '5',
                    gs: '5',
                    goals: '2',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '2',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '中正盃',
                    g: '5',
                    gs: '1',
                    goals: '2',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '7',
                    gs: '6',
                    goals: '3',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '4',
                    goals: '2',
                    asts: '3',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '4',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: "2022",
                    cup: "臺北市足球Ｕ聯賽",
                    g: "1",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制秋季聯賽",
                    g: "3",
                    gs: '3',
                    goals: "2",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市夏季主委盃草地五人制",
                    g: "2",
                    gs: '2',
                    goals: "3",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市五人制足球聯賽",
                    g: "2",
                    gs: '2',
                    goals: "1",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "包中盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市教育盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "2",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制春季聯賽",
                    g: "6",
                    gs: '5',
                    goals: "3",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "迎虎盃",
                    g: "3",
                    gs: '3',
                    goals: "3",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "A-Star聖誕盃",
                    g: "3",
                    gs: '3',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '4',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "中正主委盃",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "學童盃",
                    g: "2",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "6",
                    gs: '6',
                    goals: "8",
                    asts: "5",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "萬歲盃",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "金牛賀歲盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "扶輪社暨航源足球賽",
                    g: "5",
                    gs: '5',
                    goals: "1",
                    asts: "2",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '3',
                    goals: "4",
                    asts: "2",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "秋季大安盃",
                    g: "6",
                    gs: '5',
                    goals: "5",
                    asts: "0",
                    cs: "0"
                }]
            },
            {
                number: '23',
                name: '柏 燁',
                info: '於二年級時加入球隊，無論力量或體能在隊上都名列前矛。身兼交響樂團首席的他，為球隊提供能文能武的滿滿活力。',
                active: true,
                position: ['GK', 'RM', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '3',
                    gs: '0',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '1',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: "2022",
                    cup: "新北市少年八人制秋季聯賽",
                    g: "3",
                    gs: '0',
                    goals: "0",
                    asts: "3",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市夏季主委盃草地五人制",
                    g: "1",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "春季大安盃",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "包中盃",
                    g: "2",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制春季聯賽",
                    g: "6",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "1"
                }, {
                    year: "2022",
                    cup: "迎虎盃",
                    g: "3",
                    gs: '2',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "新北聯合盃",
                    g: "2",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "中正主委盃",
                    g: "3",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "學童盃",
                    g: "1",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "安聯小小世界盃",
                    g: "3",
                    gs: '0',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "2",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }]
            },
            {
                number: '27',
                name: '定 謙',
                info: '二年級時加入球隊，是隊上力量最強、身材最好的球員。不但把守大門的功夫了得，當需要身體對抗時，無論遇到什麼樣的對手也都不會落於下風。',
                active: true,
                position: ['GK', 'RB', 'CB', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '5',
                    gs: '2',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '3',
                    gs: '3',
                    goals: '2',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '7',
                    gs: '1',
                    goals: '3',
                    asts: '1',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '2',
                    gs: '1',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: "2022",
                    cup: "臺北市足球Ｕ聯賽",
                    g: "1",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制秋季聯賽",
                    g: "5",
                    gs: '2',
                    goals: "0",
                    asts: "1",
                    cs: "1"
                }, {
                    year: "2022",
                    cup: "新北市夏季主委盃草地五人制",
                    g: "3",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "春季大安盃",
                    g: "4",
                    gs: '1',
                    goals: "1",
                    asts: "2",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "包中盃",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制春季聯賽",
                    g: "6",
                    gs: '6',
                    goals: "0",
                    asts: "0",
                    cs: "2"
                }, {
                    year: "2022",
                    cup: "迎虎盃",
                    g: "3",
                    gs: '3',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "A-Star聖誕盃",
                    g: "3",
                    gs: '1',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "中正主委盃",
                    g: "3",
                    gs: '0',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "學童盃",
                    g: "2",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "安聯小小世界盃",
                    g: "3",
                    gs: '3',
                    goals: "2",
                    asts: "2",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "2",
                    gs: '2',
                    goals: "2",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "萬歲盃",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "金牛賀歲盃",
                    g: "1",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "扶輪社暨航源足球賽",
                    g: "3",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '3',
                    goals: "2",
                    asts: "0",
                    cs: "2"
                }, {
                    year: "2020",
                    cup: "秋季大安盃",
                    g: "5",
                    gs: '1',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }]
            },
            {
                number: '55',
                name: '宥 融',
                info: '一年級便加入球隊的早期成員，力量、鬥志和速度是他著名的武器。除了是球隊重要的大門守護神，後衛、中場與前鋒等各種角色也難不倒他。',
                active: true,
                position: ['GK', 'RB', 'LB', 'RM', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '5',
                    gs: '4',
                    goals: '0',
                    asts: '0',
                    cs: '1'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '3',
                    gs: '3',
                    goals: '2',
                    asts: '3',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '1'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '7',
                    gs: '7',
                    goals: '0',
                    asts: '1',
                    cs: '2'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '4',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }, {
                    year: "2022",
                    cup: "臺北市足球Ｕ聯賽",
                    g: "1",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制秋季聯賽",
                    g: "5",
                    gs: '5',
                    goals: "1",
                    asts: "1",
                    cs: "1"
                }, {
                    year: "2022",
                    cup: "新北市夏季主委盃草地五人制",
                    g: "3",
                    gs: '3',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市五人制足球聯賽",
                    g: "2",
                    gs: '0',
                    goals: "2",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "包中盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "中華五人制足球錦標賽",
                    g: "2",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市教育盃",
                    g: "3",
                    gs: '0',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制春季聯賽",
                    g: "6",
                    gs: '6',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "迎虎盃",
                    g: "3",
                    gs: '3',
                    goals: "5",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "A-Star聖誕盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "1",
                    cs: "1"
                }, {
                    year: "2021",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "學童盃",
                    g: "2",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "安聯小小世界盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "6",
                    gs: '6',
                    goals: "4",
                    asts: "3",
                    cs: "4"
                }, {
                    year: "2021",
                    cup: "金牛賀歲盃",
                    g: "3",
                    gs: '3',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "扶輪社暨航源足球賽",
                    g: "5",
                    gs: '5',
                    goals: "1",
                    asts: "0",
                    cs: "2"
                }, {
                    year: "2020",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '4',
                    goals: "1",
                    asts: "0",
                    cs: "1"
                }, {
                    year: "2020",
                    cup: "秋季大安盃",
                    g: "6",
                    gs: '6',
                    goals: "0",
                    asts: "1",
                    cs: "2"
                }]
            },
            {
                number: '77',
                name: '昕 叡',
                info: '雖然二年級時加入球隊時沒有足球經驗，但靠著苦練和運動天賦逐漸取得在球隊中的地位。有著用不完的能量和無比的拼勁，實用和花俏兼具的過人技巧亦讓人驚嘆',
                active: true,
                position: ['RB', 'LB', 'RM', 'LM', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '5',
                    gs: '1',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '3',
                    gs: '0',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '7',
                    gs: '0',
                    goals: '0',
                    asts: '6',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '4',
                    gs: '4',
                    goals: '9',
                    asts: '2',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '2',
                    goals: '2',
                    asts: '1',
                    cs: '0'
                }, {
                    year: "2022",
                    cup: "臺北市足球Ｕ聯賽",
                    g: "1",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制秋季聯賽",
                    g: "5",
                    gs: '4',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市夏季主委盃草地五人制",
                    g: "3",
                    gs: '0',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "春季大安盃",
                    g: "4",
                    gs: '4',
                    goals: "2",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "包中盃",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市教育盃",
                    g: "2",
                    gs: '0',
                    goals: "1",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制春季聯賽",
                    g: "6",
                    gs: '6',
                    goals: "1",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "迎虎盃",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "2",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "A-Star聖誕盃",
                    g: "2",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "新北聯合盃",
                    g: "2",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "中正主委盃",
                    g: "3",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "學童盃",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "金牛賀歲盃",
                    g: "2",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "新北聯合盃",
                    g: "3",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }]
            },
            {
                number: '97',
                name: '宇 正',
                info: '二年級下學期才加入球隊，在場上總是用速度和各種違反人體工學的動作打擊對手。從門將到前鋒等角色的轉換迅速且能穩定貢獻，是球隊最萬用的工具人之一。',
                active: true,
                position: ['GK', 'RB', 'CB', 'LB', 'RM', 'CF'],
                appearance: [{
                    year: '2023',
                    cup: '明道盃',
                    g: '5',
                    gs: '5',
                    goals: '1',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2023',
                    cup: '金兔賀歲盃',
                    g: '3',
                    gs: '2',
                    goals: '5',
                    asts: '3',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: 'Yamaha 盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '安聯小小世界盃',
                    g: '7',
                    gs: '6',
                    goals: '6',
                    asts: '3',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '新北聯合盃',
                    g: '3',
                    gs: '3',
                    goals: '1',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2022',
                    cup: '全國學童盃',
                    g: '4',
                    gs: '4',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: "2022",
                    cup: "臺北市足球Ｕ聯賽",
                    g: "1",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制秋季聯賽",
                    g: "4",
                    gs: '4',
                    goals: "1",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市五人制足球聯賽",
                    g: "2",
                    gs: '1',
                    goals: "1",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "包中盃",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "中華五人制足球錦標賽",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "臺北市教育盃",
                    g: "3",
                    gs: '1',
                    goals: "3",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "新北市少年八人制春季聯賽",
                    g: "5",
                    gs: '5',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2022",
                    cup: "迎虎盃",
                    g: "3",
                    gs: '3',
                    goals: "1",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "A-Star聖誕盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '4',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "中正主委盃",
                    g: "3",
                    gs: '2',
                    goals: "2",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "學童盃",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "安聯小小世界盃",
                    g: "3",
                    gs: '3',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "6",
                    gs: '3',
                    goals: "14",
                    asts: "6",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "萬歲盃",
                    g: "2",
                    gs: '2',
                    goals: "3",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "金牛賀歲盃",
                    g: "3",
                    gs: '3',
                    goals: "2",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "扶輪社暨航源足球賽",
                    g: "5",
                    gs: '0',
                    goals: "1",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "新北聯合盃",
                    g: "4",
                    gs: '3',
                    goals: "1",
                    asts: "1",
                    cs: "0"
                }, {
                    year: '2020',
                    cup: '新北迷你盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: "2020",
                    cup: "秋季大安盃",
                    g: "6",
                    gs: '3',
                    goals: "3",
                    asts: "0",
                    cs: "0"
                }]
            },
            {
                number: '2',
                name: '定 宸',
                active: false,
                position: ['RB', 'CB'],
                appearance: [{
                    year: '2021',
                    cup: '春季大安盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '萬歲盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北聯合盃',
                    g: '2',
                    gs: '1',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北迷你盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '秋季大安盃',
                    g: '4',
                    gs: '1',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }]
            },
            {
                number: '8',
                name: '翊 愷',
                active: false,
                position: [],
                appearance: [{
                    year: '2021',
                    cup: '安聯小小世界盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '春季大安盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2021',
                    cup: '萬歲盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北聯合盃',
                    g: '1',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北迷你盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }]
            },
            {
                number: '11',
                name: '定 緯',
                active: false,
                position: [],
                appearance: [{
                    year: '2021',
                    cup: 'A-Star聖誕盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }, {
                    year: '2020',
                    cup: '新北迷你盃',
                    g: '2',
                    gs: '2',
                    goals: '0',
                    asts: '0',
                    cs: '0'
                }]
            },
            {
                number: '22',
                name: '明 澤',
                active: false,
                position: ['RB', 'LB'],
                appearance: [{
                    year: "2021",
                    cup: "安聯小小世界盃",
                    g: "2",
                    gs: '0',
                    goals: "0",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "春季大安盃",
                    g: "2",
                    gs: '0',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "萬歲盃",
                    g: "2",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2021",
                    cup: "金牛賀歲盃",
                    g: "3",
                    gs: '2',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "新北聯合盃",
                    g: "2",
                    gs: '0',
                    goals: "0",
                    asts: "1",
                    cs: "0"
                }, {
                    year: "2020",
                    cup: "秋季大安盃",
                    g: "6",
                    gs: '1',
                    goals: "0",
                    asts: "0",
                    cs: "0"
                }]
            },
            {
                number: '30',
                name: '品 叡',
                active: false,
                position: [],
                appearance: [{
                    year: '2020',
                    cup: '新北聯合盃',
                    g: '2',
                    gs: '0',
                    goals: '0',
                    asts: '1',
                    cs: '0'
                }]
            }
        ]
    },
    methods: {
        numberFilter: function(players) {
            var min = this.minNumber < 10 ? '0' + this.minNumber : this.minNumber;
            var max = this.maxNumber < 10 ? '0' + this.maxNumber : this.maxNumber;

            if (!!this.minNumber && !!this.maxNumber) {
                return players.filter((player) => {
                    var playerNum = player.number < 10 ? '0' + player.number : player.number
                    return playerNum >= min && playerNum <= max;
                })
            } else {
                return this.players
            }
        },
        positionFilter: function(players) {
            if (this.selectedPosition.length > 0) {
                return players.filter((player) => {
                    return player.position.indexOf(this.selectedPosition) !== -1;
                });
            } else {
                return this.players
            }
        },
        nameFilter: function(players) {
            if (!!this.searchText) {
                return players.filter((player) => {
                    return player.name.includes(this.searchText);
                });
            } else {
                return this.players
            }
        },
        resetFilter: function() {
            this.searchText = null;
            this.minNumber = null;
            this.maxNumber = null;
            this.selectedPosition = [];
            this.sortType = 'number'
        },
        setSortType: function(val) {
            this.sortType = val
        }
    },
    computed: {
        playerFilter: function(type) {
            let nameFilteredArray = this.nameFilter(this.players)
            let positionFilteredArray = this.positionFilter(this.players)
            let numberFilteredArray = this.numberFilter(this.players)
            let allFilteredArray = nameFilteredArray.concat(positionFilteredArray).concat(numberFilteredArray)
            // console.log(nameFilteredArray, positionFilteredArray, numberFilteredArray, allFilteredArray)

            var counts = {}

            for (var i = 0; i < allFilteredArray.length; i++) {
                var num = allFilteredArray[i].number
                counts[num] = counts[num] ? counts[num] + 1 : 1
            }

            var result = []
            for (var key in counts) {
                if (Object.prototype.hasOwnProperty.call(counts, key) && counts[key] > 2) {
                    for (var i = 0; i < allFilteredArray.length; i++) {
                        if (allFilteredArray[i].number === key) {
                            result.push(allFilteredArray[i])
                        }
                    }
                }
            }

            filteredResult = _.uniq(result, 'number')

            function sumStat(o, type) {
                let sum = _.sumBy(o.appearance, app => {
                    return parseInt(app[type])
                })
                return sum
            }

            filteredResult = filteredResult.map(v => ({ ...v,
                totalMatches: sumStat(v, 'g'),
                totalGS: sumStat(v, 'gs'),
                totalGoals: sumStat(v, 'goals'),
                totalAsts: sumStat(v, 'asts'),
                totalCS: sumStat(v, 'cs')
            }))

            type = this.sortType

            if (type === 'number') {
                filteredResult = _.orderBy(filteredResult, function(obj) {
                    return parseInt(obj[type], 10);
                })
            } else {
                filteredResult = _.orderBy(filteredResult, function(obj) {
                    return parseInt(obj[type], 10)
                }, 'desc')
            }

            // console.log(filteredResult)

            return {
                active: _.filter(filteredResult, ['active', true]),
                retire: _.filter(filteredResult, ['active', false])
            }
        },
        yearFilter: function(app, val) {
            let appYear = app
            return function(appYear) {
                return appYear
            }
        }
    }
})